### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by deepslam** [shekharramola/react-wheel-of-prizes#3] opened 2020-12-15 19:58 UTC
Hello!

I'm trying to install it with React 17 in my package.json.
But it crashes with the message:

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-wheel-of-prizes@1.0.6

Please, fix it if you can :)

Thanks a lot!

**Comment by shekharramola** [comment] 2021-01-11 06:37
Hi @deepslam ,

I am not able to reproduce this with the react 17 version. can you please tell me your exact configuration?
https://codesandbox.io/s/prod-wind-d3veh?file=/src/App.js
![image](https://user-images.githubusercontent.com/13901619/104152421-82be2080-5405-11eb-82c7-705543c426e8.png)

**Comment by git-angelo** [comment] 2021-03-01 09:41
I had a similar error when my project was opened in my IDE.

After closing it and running "npm install --save react-wheel-of-prizes" again, it worked.

**Closed** 2021-03-08 16:07 UTC
